sudo: required
dist: trusty

language: node_js
node_js: 6

os:
  - linux
  
install:
  - npm install lix@15.2.0-alpha.2 -g
  - lix download
  - haxelib install travix

script:
  - haxelib run travix js
